### ISSUE TITLE
Need help? 

### ISSUE THREAD

**Issue by xlogix** [Arubadel/Arubadel#1]
Hi,
My dad is a user of i8252 and I would like to help you in the app building process. Can you list out the issues?

**Comment by androidlover5842** [comment]
this app has old ui and codes are so hard to understand for normal users i just want  a cool ui

**Comment by xlogix** [comment]
Oh okay! Will work on it.

**Comment by androidlover5842** [comment]
https://github.com/Arubadel/Arubadel/invitations accept the inviation so you can commit changes
